server:
  port: 5031

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangyangv587/shadow-config.git

  rabbitmq:
    host: 120.78.165.252
    port: 5672
    username: guest
    password: guest
#/{application}/{profile}[/{label}]
#
#/{application}-{profile}.yml
#
#/{label}/{application}-{profile}.yml
#
#/{application}-{profile}.properties
#
#/{label}/{application}-{profile}.properties
#application就是配置文件的名字， profile就是对应的环境 label就是不同的分支