server:
  port: 5011
  servlet:
    context-path: /

spring:
  application:
    #此实例注册到Eureka实例的name
    name: eureka-user

#配置负载均衡方式为随机轮询
EUREKA-ORDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#feign整合hystrix
feign:
  hystrix:
    enabled: true

#hystrixdashbord
management:
  endpoints:
    web:
      exposure:
        include: '*'


hystrix:
  command:
    default:
      execution:
        isolation:
          #隔离策略，默认是Thread, 可选Thread｜ Semaphor
          strategy: Thread
          thread:
            #命令执行超时时 间，默认1000ms
            timeoutInMilliseconds: 2000
            #发生超时时是否中断， 默认true
            interruptOnTimeout: true
        timeout:
          #执行是否启用超时时间，默认为true
          enabled: true
      circuitBreaker:
        #强制打开熔断器，如果打开这个开关，那么拒绝所 有request，默认false
        forceOpen: false
        #强制关闭熔断器 如果这个开关打开，circuit将 一直关闭且忽略
        forceClosed: false

#eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/
  instance:
    #此实例注册到Eureka服务端的唯一实例ID
    instance-id: eureka-user01
    #是否显示ip地址
    prefer-ip-address: true
    #客户端需要多长时间发送心跳给服务端，证明它还活着，默认为30s
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在接收到客户端最后一次发出心跳后，需要等待多久时间才可以将此实例删除，默认为90s
    lease-expiration-duration-in-seconds: 90