server:
  port: 5041

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/
  instance:
    instance-id: zuul-01
    prefer-ip-address: true

spring:
  application:
    name: zuul