server:
  port: 5011

spring:
  application:
    #此实例注册到Eureka实例的name
    name: eureka-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/
  instance:
    #此实例注册到Eureka服务端的唯一实例ID
    instance-id: eureka-user01
    #是否显示ip地址
    prefer-ip-address: true
    #客户端需要多长时间发送心跳给服务端，证明它还活着，默认为30s
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在接收到客户端最后一次发出心跳后，需要等待多久时间才可以将此实例删除，默认为90s
    lease-expiration-duration-in-seconds: 90