server:
  port: 5031

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangyangv587/shadow-config.git


---

spring:
  application:
    name: a